unstable_features = true

group_imports = "StdExternalCrate"
imports_granularity = "One"
imports_layout = "HorizontalVertical"

merge_derives = true
reorder_impl_items = false
newline_style = "Unix"
style_edition = "2024"

comment_width = 100
inline_attribute_width = 100
wrap_comments = true

fn_single_line = false
format_strings = true
trailing_comma = "Never"

hex_literal_case = "Upper"
use_small_heuristics = "Max"

use_field_init_shorthand = true
